import {
  BarChart3,
  Bookmark,
  Briefcase,
  ClipboardList,
  Euro,
  Home,
  MessageSquare,
  Plus,
  Search,
  Star,
  Upload,
  User,
  Users,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from '@/components/ui/Icon';

const MAP: Record<IconName, LucideIcon> = {
  home: Home,
  search: Search,
  clipboard: ClipboardList,
  chat: MessageSquare,
  user: User,
  bookmark: Bookmark,
  upload: Upload,
  euro: Euro,
  star: Star,
  plus: Plus,
  briefcase: Briefcase,
  users: Users,
  chart: BarChart3,
  calendar: Home,
  clock: Home,
  pin: Home,
  bell: Home,
  file: ClipboardList,
  check: Home,
  x: Home,
  chevright: Home,
  chevleft: Home,
  arrowup: Home,
  arrowdown: Home,
  menu: Home,
  layers: Home,
  trend: Home,
  gauge: Home,
  flame: Home,
  heart: Home,
  insta: Home,
  x_social: Home,
  linkedin: Home,
  shield: Home,
  sliders: Home,
  bolt: Home,
};

export function navIcon(name: IconName): LucideIcon {
  return MAP[name] ?? Home;
}
